# Generated by Django 3.0.4 on 2021-08-17 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_de_inflado',
            field=models.DateField(default=datetime.date(2021, 6, 17), null=True),
        ),
    ]
