# Generated by Django 3.0.4 on 2021-08-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20210820_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='compañia',
            field=models.CharField(default='Demo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='compañia',
            field=models.CharField(default='Demo', max_length=200, null=True),
        ),
    ]
