# Generated by Django 3.2.6 on 2021-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_auto_20210821_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='compañia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
