# Generated by Django 3.0.4 on 2021-09-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_excel_compañia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=100)),
                ('compañia', models.CharField(max_length=200, null=True)),
                ('fecha_de_inflado', models.DateField(blank=True, null=True)),
                ('tiempo_de_inflado', models.FloatField(blank=True, default=2, null=True)),
                ('presion_de_entrada', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_de_salida', models.IntegerField(blank=True, default=100, null=True)),
                ('presion_establecida', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='excel',
            name='compañia',
            field=models.CharField(default='Demo', max_length=200, null=True),
        ),
    ]
