# Generated by Django 3.0.4 on 2021-09-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_auto_20210906_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
