# Generated by Django 3.0.4 on 2021-09-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20210907_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=200),
        ),
    ]
