# Generated by Django 3.0.4 on 2021-09-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_auto_20210907_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default='Demo', max_length=200, null=True),
        ),
    ]
